steps:
  # Julia versions

  - label: "Julia 1.5, CUDA 11.2"
    plugins:
      - JuliaCI/julia#v1:
          version: 1.5
      - JuliaCI/julia-test#v1:
          test_args: "--thorough"
      - JuliaCI/julia-coverage#v1:
          codecov: true
          dirs:
            - src
    agents:
      queue: "tng"
      cuda: "11.2"
      cap: "recent"
    env:
      JULIA_CUDA_VERSION: '11.2'
      JULIA_CUDA_USE_BINARYBUILDER: 'true'
    if: build.message !~ /\[skip tests\]/
    timeout_in_minutes: 120

  - label: "Julia 1.6, CUDA 11.2"
    plugins:
      - JuliaCI/julia#v1:
          version: 1.6-nightly
      - JuliaCI/julia-test#v1:
          test_args: "--thorough"
      - JuliaCI/julia-coverage#v1:
          codecov: true
          dirs:
            - src
    agents:
      queue: "tng"
      cuda: "11.2"
      cap: "recent"
    env:
      JULIA_CUDA_VERSION: '11.2'
      JULIA_CUDA_USE_BINARYBUILDER: 'true'
    if: build.message !~ /\[skip tests\]/
    timeout_in_minutes: 120

env:
  JULIA_PKG_SERVER: "" # it often struggles with our large artifacts
  CODECOV_TOKEN: "3ec2d5ff-c348-49bd-804b-0d05e92881de"
